#!/usr/bin/env bash
# script to print hour from 0 to 12
n=0
while [ $n -le 12 ]
do
    	echo "Hour: $n"
    	i=1
    	while [ $i -le 59 ]
    	do
        	echo "$i"
        	i=$((i+1))
    	done
	n=$((n+1))
done
